name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: commandToBuildYourProject.sh
      - name: Dockerize
        if: success()
        uses: manusa/actions-publish-docker@v1.1.2
        with:
          name: organization/image_name
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
